---
title: "TeviHub"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: simplex
    logo: images/SWEEPLOGO.png
---
<script>
$('.navbar-logo').wrap('<a href="http://www.sweep.ac.uk"> target=_blank');
</script>

```{r, setup, include=FALSE}
#   rmarkdown::render_site()
#   https://jrmosedale.github.io/dashboard/

library(flexdashboard)

library(raster)
library(leaflet)
library(magrittr)
library(colorspace)
library(rgeos)
library(ggplot2)
library(rgdal)
library(sf)
library(units)
library(leaflet.extras)

################################################
# Directories
###############################################
# if (Sys.getenv("HOME")=="/Users/jm622") in.root<-paste0(Sys.getenv("HOME"),"/OneDrive - University of Exeter/Rprojects/EG4B/app/")
in.root<-"data/"

################################################
# Load functions 
###############################################
source("Rscripts/functions.R")

# Presentation functions etc
csa_icons <- function() {
  awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = "green")
}

cta_icons<- function() {
  awesomeIcons(
    icon = 'ios-close',
    iconColor = 'black',
    library = 'ion',
    markerColor = "blue"
  )
}

tevi_icons <- function(tevibus){
  awesomeIcons(
    icon = tevibus$Icon,
    iconColor = 'black',
    library = 'fa',
    markerColor = tevibus$Colour
  )
}
```

Section 1 Business Locations and Engagement 
============================================================================================
Businesses participating (as of September 2018) in the [Tevi](https://tevi.co.uk) programme, award winners of the [Cornwall Sustainability Awards](https://www.cornwallsustainabilityawards.org) (2004-17) and [Cornwall Tourism Awards](http://www.cornwalltourismawards.org.uk) (2018 only).
Click on marker for further information.



Column {.tabset}
------------------------------------------------------------------------------------------------------------

### Map 1 Tevi Businesses

```{r,context='data', include=FALSE}

############################################
# LOAD Business data and prepare for mapping
############################################

# Business data
tevibus<- st_read(paste0(in.root,"tevibus.shp"))
csawinners<-st_read(paste(in.root,"csawinners.shp",sep=""))
cta2018<- st_read(paste0(in.root,"cta2018.shp"))
st_crs(tevibus)<-st_crs(27700)
st_crs(csawinners)<-st_crs(27700)
st_crs(cta2018)<-st_crs(27700)

```


```{r,echo=FALSE,out.width='100%', fig.align='center'}

# Create popup message
tevi.popup<-paste("<b>",tevibus$Enterprise,"</b>","<br>","Sector: ",tevibus$Sector,"<br>","Tevi Status: ",tevibus$Status,"<br>","CSA Status:",tevibus$CSA_status) 

teviplot<- prepare_sf_for_leaflet(tevibus)

leaflet() %>% 
  setView(lng = -4.9, lat = 50.4, zoom = 10)  %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addScaleBar() %>%
  addAwesomeMarkers(data=teviplot,
                    icon=tevi_icons(teviplot),  
                    label = ~as.character(Enterprise),
                    popup = tevi.popup
)


```

### Map 2 Cornwall Sustainability and Tourism Award Winners

```{r,  echo=FALSE}
# Create popup message
csa.popup<-paste("<b>",csawinners$Business,"</b>","-",csawinners$Award,csawinners$Year)
cta.popup<-paste("<b>",cta2018$Enterprise,"</b>","-",cta2018$Award,cta2018$Year)


leaflet() %>% 
setView(lng = -4.9, lat = 50.4, zoom = 10)  %>%
addProviderTiles("OpenStreetMap.Mapnik") %>%
addScaleBar() %>%
addAwesomeMarkers(data=prepare_sf_for_leaflet(csawinners),
                  icon=csa_icons(), 
                  label = ~as.character(Business),
                  popup = csa.popup,
                  group= "CSA businesses")  %>%
addAwesomeMarkers(data=prepare_sf_for_leaflet(cta2018),
                  icon=cta_icons(), 
                  label = ~as.character(Enterprise),
                  popup = cta.popup,
                  group ="CTA businesses" )  %>%
addLayersControl(
                  overlayGroups =c("CSA businesses", "CTA businesses"),
                  options = layersControlOptions(collapsed=FALSE)  
)  %>%
hideGroup(c("CTA businesses"))


```

