---
title: "Priority Map Doc 1"
author: "JMosedale"
date: "07/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#### Mapping of environmental assets for Cornwall  
##### Overview of product  
**Purpose**  
The purpose is to generate strategic prioritization maps of existing environmental ‘assets’ across mainland Cornwall.  High priority areas correspond to those areas where current habitats, and the ecosystem services they provide, merit protection from any development or change in land use that will undermine these assets.  
A further goal of the methodology is to be able to experiment with, and demonstrate, key factors affecting prioritizations. Therefore, the approach is shaped around an methodology which can be readily modified and which allows easy updating/replacement of source data layers or adjustments to the perceived importance of different services, and which can be applied to different spatial areas and resolutions.   
  
**Factors determining prioritization**  
Initial approach will prioritize areas based on:   
• Existing habitat and/or land cover type  
• Habitat distribution and connectivity  
• Species presence distributions (if suitable data available) or area designations based on their biodiversity value (e.g. County wildlife sites)  
• Key ecosystem service provision  
  
**Additional factors that can be accounted for include:**  
• Suitability for other land uses such as agricultural grae, proximity to built-up areas.   
• Facilitating factors such as non-statutory designations, land ownership, and landscape characteristics.  
  
The methodology assigns highest prioritization/ranking to statutory protected areas such as SSSI's, local and national nature reserves, SACs, SPAs).    

The rankings assigned to a grid cell are not independent. The reasons for this are driven by the need to account for habitat connectivity. There is no value to only ‘partly’ protecting or planting a corridor that links existing habitats – therefore the value of each ‘cell’ along the corridor depends on the habitat of the whole corridor being maintained. In terms of the prioritization maps this means that the ranking of a cell assumes that all other cells of an equal or greater ranking are prioritized.
  
**Other methodology notes**  
• Initial prioritization scale = 100 metres (will add finer spatial resolution mapping if deemed desirable & feasible).   
• Zonation software will be applied to determine the prioritization – a system that that been widely used for land use and conservation planning and allows the iterative adjustment of underlying parameters such as relative weighting of different factors.  
• The connectivity of protected areas is accounted for in the way prioritizations are calculated within Zonation.  
  
**Important limitations:**  
• The value of ecosystem services provided are based upon the current distribution of ecosystem services, habitats and service ‘demand’ factors such as populations and key activities like aquaculture.    
• Current outputs do not consider future demand for services (which might be created for example, by future building developments impacting the demand for ecosystem services).  
  
#####Steps and notes on data requirements  
  
**1 Define area for prioritization**  
Initial focus on prioritization for whole of Cornwall mainland, but can later be applied to:  
• AONB area only  
• Single Catchment eg Fowey  
• Single Neighbourhood  
• Balancing different prioritization scales e.g. neighbourhood and county prioritizations.  
    
**2.  Define irreplaceable habitats & existing protected areas:** 
• Existing designated areas – SSSIs (condition), SAC, SPA, local reserves, County Wildlife sites, National marine conversation zones    
• Option of defining other irreplaceable/critical habitats through habitat data.  
  
**3 Biodiversity importance**  
Data layers describing the distribution of habitats and (if available) species. The relative importance of different habitats will be represented through a weighting system. 
3a.  Habitat data
• Landcover/ habitat distribution (CEH landcover, Nat England Priority habitat – later to include Sentinel derived landcover data)
• Condition data if/when available (initially assume constant unless suitable data identified)
• Linear features layers such as river banks, hedgerows (ERCCIS data)
• Fragmentation/Connectivity – is integrated into the Zonation methodology but there is also the option of explicitly generating layers describing connectivity through various indices/methods. 
  
3b. Non-statutory designations based on biodiversity value  
• Areas defined as County wildlife sites (ERCCIS data).  
  
**NB:** New landcover/habitat data for Cornwall will replace the data mentioned above during 2019.  
  
**4. Ecosystem services**  
Initially only a small subset of services likely to be explicitly included:  
o Soil erosion  
o Flood mitigation   
o Water quality (for drinking, bathing and aquaculture waters)  
o Carbon storage  
o Pollination  
List can be expanded as and when suitable methods are developed.   
There are methodological challenges – particularly in capturing the ‘demand’ for services eg impacts of floods, pollinator requirements of agriculture, accessibility of services (see below) etc.  
As with habitat and species data, weighting can be applied to describe the relative importance ascribed to different ecosystem services.  
  
**5. Integrating accessibility as a factor in service provision (not yet implemented)** 
The provision of some ecosystem services depends on access / visitation to greenspace including a range of cultural/recreational/health benefits.  
Some simple options to integrate might be:  
• Weighting according to size of nearby resident population (which will favour protected areas close to population centres).  
• Balancing prioritizations at different spatial scales (which will favour wider distribution of no-go areas).   
• Footpaths/hedgerows – possess habitat corridor value  
  
**6. Facilitation and Constraint factors (optional)**    
There are a huge range of factors could either facilitate or restrain the designation of no-go areas. 
For example:  
• Alternative use & land cost constraints:  
o Negative weighting for built-up areas   
o Agricultural land grade or prices  
o Existing / recent planning commitments – allocation areas.  
• Land ownership, management & designations:  
o Ownership: National Trust, Council assets, NGO assets, CWT, RSPB, Duchy of Cornwall, Tregothan estate, Trewithen, St Albans, other?  
o Landscape or Heritage designation (could constrain or facilitate?)  
o High-level agri-environment stewardship schemes.  
o Open access to land?   
• Physical constraints on opportunities:  
o Elevation/topography/soil type/inter-tidal zone?  
   
Factors could be applied as weighted layers as part of the prioritization analysis or as simple masks pre/post-analysis.  